### ISSUE TITLE
use SCT instead of RNA assay for  create_scMuffinList ?

### ISSUE THREAD

**Issue by atzatsos** [emosca-cnr/scMuffin#1]
Thank you for generating this package. 
I analyzed my data using Seurat (v4.3) and SCTtransfrom. I was wondering whether I can use the "SCT" instead of "RNA" assay for generating the scML.

scML <- create_scMuffinList(counts = GetAssayData(seu_obj_1, assay = "RNA", slot = "counts"), 
                            normalized = GetAssayData(seu_obj_1, assay = "RNA", slot = "data"))

best,
alex

**Comment by emosca-cnr** [comment]
Dear Alex,

thanks for your comment. Most of the analyses available in scMuffin require gene expression data that are normalized in log space. The slot "data" of "SCT" assay contains log1p(counts), where counts are "corrected" counts (see https://satijalab.org/seurat/reference/sctransform). So, I guess setting normalized = GetAssayData(seu_obj_1, assay = "SCT", slot = "data")) should give meaningful results in downstream analyses. Consider doing some test...

Best,
Ettore

**Comment by atzatsos** [comment]
Thank you! I will try both ways. 

I have another question. I want to use CNV_analysis for a mouse dataset. I did BiocManager::install("org.Mm.eg.db") and I type
scML <- CNV_analysis(scML, gene_ann = org.Mm.eg.db) but I got the following error. Any suggestions?

best,
alex


Genes-by-cells matrix size 14978 3990 
Filtering... done
Genes-by-cells matrix size 11549 3990 
Preprocess object to calculate CNV...
User-provided gene annotations...
Can't use the given annotation: proceeding with org.Hs.eg.db...
Retrieving gene locations...
Genes with known location 6 
Genes in chromosomes:
 1  6  9 11 13 19 
 1  1  1  1  1  1 
Excluding chromosomes 1 6 9 11 13 19 
Consider reducing wnd_size parameter.
Calculating CNV...
Chromosome NA ...
Error in ans[[i]] : subscript out of bounds

**Comment by emosca-cnr** [comment]
"gene_ann" should be a "data.frame with gene annotation with mandatory columns "Chromosome", "symbol" and "pos" (genomic location)". So, at the moment, of you want to use a custom annotation you should create a data.frame with: "Chromosome", "symbol", "pos" columns. You can do that using org.Mm.eg.db. 

library(org.Mm.eg.db)
gene_locations <- as.data.frame(org.Mm.egCHRLOC)
temp <- as.data.frame(org.Mm.egCHRLOCEND)
eg2sym <- as.data.frame(org.Mm.egSYMBOL)

gene_locations <- merge(eg2sym, gene_locations, by="gene_id", sort=F)
gene_locations <- merge(gene_locations, temp, by=c("gene_id", "Chromosome"), sort=F)
gene_locations$pos <- apply(abs(gene_locations[, c("start_location", "end_location")]), 1, min) 
gene_locations$gene_id <- gene_locations$start_location <- gene_locations$end_location <- NULL
gene_locations <- unique(gene_locations)

scML <- CNV_analysis(scML, gene_ann = gene_locations)

I've just updated the package to v1.1.6. Let me know if it works!
Best,
